services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=user
  bucket:
    image: quay.io/minio/minio:RELEASE.2025-02-07T23-21-09Z-cpuv1
    container_name: bucket
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_admin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
volumes:
  pg-data:
    driver: local
  minio-data:
    driver: local
